### ISSUE TITLE
Open Source CUDA work

### ISSUE THREAD

**Issue by unzvfu** [n1analytics/cuda-fixnum#1]
Tasks required before cuda-fixnum & cuda-paillier can be released:

- [x] clean up cuda-fixnum kernel programming interface (#3)
- [x] write wrapper for conveniently manipulating device arrays (#4)
- [x] migrate existing test suite (#5)
- [x] migrate modexp implementation (#9)
- [x] implement Paillier in terms of the updated cuda-fixnum interface (#10)
- [x] write benchmark (#11)
- [x] document library structure and use (#14)
- [x] DAP admin thing
