### ISSUE TITLE
Migrate existing test suite

### ISSUE THREAD

**Issue by unzvfu** [n1analytics/cuda-fixnum#5]
The existing test suite exercised the modexp code via a Python wrapper. I want rather to have a C++-based test suite for easier debugging and (eventually) coverage reporting.

- [x] generate test input/expected output values using Python (#6)
- [x] use generated test input/output in C++ test suite (#7)
- [ ] ~have tests run automatically on Travis (#8)~
